package com.myfirstproject;

import com.utilities.TestBase;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;

public class Day06_02Alerts extends TestBase {

    /*
    What is alert?  (UYARI)
    - it is pop up that is generated by JS
    - it is used to give informational messages.
    - when there is an alert pop up on the page , we must handle the alert otherwise we cannot move on
   How do you handle alerts?
   First we cannot inspect JS alerts. We should fist switch to the alert and use accept() to click OK,
                                                                                 dismiss() to click CANCEL,
                                                                                 sendKeys() to type,
                                                                                 getText() to get the TEXT from the alert.
    - Swtich to alert
      then use accept to click,
      dismiss to click Cancel,
      getText to get the text,
      and sendKeys to type on the alert.



      ***  ALERT  ***
  *    accept() Same as clicking OK of an alert.
      driver.switchTo().alert().accept();

  *   dismiss() Same as clicking Cancel of an alert.
      driver.switchTo().alert().dismiss();

  *   gettext() To get the alert message of the alert.
      driver.switchTo().alert().gettext();

  *   sendKeys()("Text") To send a text into alert text box
      driver.switchTo().alert().sendkeys("Text")

      switchTo() - degistir
     */

    @Test
    public void acceptAlert() throws InterruptedException {
      /*
      H/W
      acceptAlert() => click on the first alert,
     verify the text “I am a JS Alert” ,
     click OK ,
     and Verify “You successfully clicked an alert”
     */

        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        Thread.sleep(3000);
        driver.findElement(By.xpath("//button[@onclick='jsAlert()']")).click();
        Thread.sleep(3000);
        String actualResult = driver.switchTo().alert().getText();
        Thread.sleep(3000);
        Assert.assertEquals("I am a JS Alert", actualResult);

        driver.switchTo().alert().accept();
        Thread.sleep(3000);
        String actualResult1 = driver.findElement(By.id("result")).getText();
        Assert.assertEquals("You successfully clicked an alert", actualResult1);
        Thread.sleep(3000);

    }

    @Test
    public void dismissAlert() throws InterruptedException {


        /*
     H/W
     dismissAlert()=> click on the second alert,
     verify text "I am a JS Confirm”,
     click cancel,
     and Verify “You clicked: Cancel”
       */


        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        Thread.sleep(3000);

        driver.findElement(By.xpath("//button[@onclick='jsConfirm()']")).click();
        String actualAlertText = driver.switchTo().alert().getText();
        Thread.sleep(3000);

        Assert.assertEquals("I am a JS Confirm", actualAlertText);
        // click CANCEL
        driver.switchTo().alert().dismiss();
        Thread.sleep(3000);

        String actualResult = driver.findElement(By.id("result")).getText();
        String expectedResult = "You clicked: Cancel";
        Assert.assertEquals(expectedResult, actualResult);

    }

    @Test
    public void sendKeysAlert() throws InterruptedException {


        /*
         sendKeysAlert()=> click on the third alert,
         verify text “I am a JS prompt”,
         type “Hello World”,
          click OK,
         and Verify “You entered: Hello World”
         */

        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        // click on the third alert
        driver.findElement(By.xpath("//button[@onclick='jsPrompt()']")).click();
        Thread.sleep(3000);

        // verify text “I am a JS prompt”
        String actualAlertText = driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS prompt", actualAlertText);
        Thread.sleep(3000);

        // type “Hello World”
        driver.switchTo().alert().sendKeys("Hello World");
        Thread.sleep(3000);
        // click OK
        driver.switchTo().alert().accept();
        Thread.sleep(3000);

        // and Verify “You entered: Hello World”
        String actualResultText = driver.findElement(By.id("result")).getText();
        Assert.assertEquals("You entered: Hello World", actualResultText);
        Thread.sleep(3000);

    }
}











