package com.myfirstproject;

import com.utilities.TestBase;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;

public class Day06_02Alerts extends TestBase {

    /*
    What is alert?
    - it is pop up that is generated by JS
    - it is used to give informational messages.
    - when there is an alert pop up on the page , we must handle the alert otherwise we cannot move on
   How do you handle alerts?
    - Swtich to alert
      then use accept to click,
      dismiss to click Cancel,
      getText to get the text,
      and sendKeys to type on the alert.
     */

    @Test
    public void acceptAlert() {
/*
H/W
acceptAlert() => click on the first alert,
verify the text “I am a JS Alert” ,
click OK ,
and Verify “You successfully clicked an alert”
 */
    }

    @Test
    public void dismissAlert() {
/*
H/W
dismissAlert()=> click on the second alert,
verify text "I am a JS Confirm”,
click cancel,
and Verify “You clicked: Cancel”
 */
    }

    @Test
    public void sendKeysAlert() {
/*
sendKeysAlert()=> click on the third alert,
verify text “I am a JS prompt”,
type “Hello World”,
click OK,
and Verify “You entered: Hello World”
Collapse
 */

        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        // click on the third alert
        driver.findElement(By.xpath("//button[@onclick='jsPrompt()']")).click();

        // verify text “I am a JS prompt”
       String actualAlertText = driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS prompt",actualAlertText);

       // type “Hello World”
        driver.switchTo().alert().sendKeys("Hello World");

        // click OK
        driver.switchTo().alert().accept();

        // and Verify “You entered: Hello World”
      String actualResultText =  driver.findElement(By.id("result")).getText();
      Assert.assertEquals("You entered: Hello World",actualResultText);

    }
}











